### ISSUE TITLE
How is this used?

### ISSUE THREAD

**Issue by ghost** [FurkanToprak/OkapiBM25#5]
I can't get this to work

```
var BM25 = require("okapibm25").BM25;
var documents = [
    "place",
    "documents",
    "here",
    "Each test document will be searched with the keywords specified below.",
];
var query = ["keywords", "of", "your", "query."];
// A numerical scoring will be returned.
var result = BM25(documents, query, { k1: 1.3, b: 0.9 });
console.log(result);
```

====
```
var result = BM25(documents, query, { k1: 1.3, b: 0.9 });
             ^

TypeError: BM25 is not a function
```

**Comment by FurkanToprak** [comment]
Hey @atorsvn. Thanks for contacting me. As this is a Typescript library, you cannot use `okapibm25` out-of-the-box.

You need to do one of the following: 

# 1) Typescript Approach
* Install Typescript via `npm install --save-dev typescript`
* Create a typescript file 
```
// index.ts
import BM25 from "okapibm25";
const documents = [
  "place",
  "documents",
  "here",
  "Each test document will be searched with the keywords specified below.",
];
const query = ["keywords", "of", "your", "query."];
// A numerical scoring will be returned.
const result = BM25(documents, query, { k1: 1.3, b: 0.9 });
console.log(result);
```
Next, compile and run:
`npx ts-node index.ts`
You should get the following output:
```
[ 0, 0, 0, 0.5760464234664954 ]
```

# 2) Node.js experimental module support
* Ensure you have an up-to-date Node.js version.
* Create a .mjs file:
```
// index.mjs
import BM25 from "okapibm25";

const documents = [
  "place",
  "documents",
  "here",
  "Each test document will be searched with the keywords specified below.",
];
const query = ["keywords", "of", "your", "query."];
// A numerical scoring will be returned.
const result = BM25(documents, query, { k1: 1.3, b: 0.9 });
console.log(result);
```
Run the module using this `node --experimental-modules index.mjs`

# Other options
## 3) Use esm
## 4) Use babel
I'm not very well-versed on these options, but see the [following issue for examples](https://github.com/dgreif/ring/issues/155#issuecomment-543705636).

**Comment by FurkanToprak** [comment]
Of course, you could always just download the compiled javascript from this repository and use it locally.

**Comment by ghost** [comment]
Please forgive m y ignorance, I'm fairly new to much of this. Which files
specifically are the compiled JS?

**Comment by ghost** [comment]
I'm trying to use this in a discord bot for GPT contextual calibration as a search on a corpus to grab relevant data to be used as a context suggestion in a prompt. I've done it with the python rank_bm25 and this looks similar.  If I can get it down to a simple javascript function call that would be fabulous.

**Comment by FurkanToprak** [comment]
Hey @atorsvn it sounds like you have a large-ish project on your hands. 

### My preference: Typescript + npm
So that your project is as simple as possible, I recommend you follow the steps for Typescript and use `npm` to initialize a project and install the package. It might look a little daunting at first, but it's very similar to `python` and `pip`.  This will also allow you to use many libraries.

### Your preference: Regarding compiled JS
The compiled JS doesn't exist anymore (sorry, I forgot about this). Instead, if you want to use the existing code, the easiest thing for you to do would probably be to copy `BM25.ts`, rename it to `BM25.js`, and remove all of the Typescript annotations (all of the parameter types and return types). 

If you don't want to manually convert the typescript, you can compile the `ts` to `js` file using `tsc`. [Learn more here](https://www.typescriptlang.org/docs/handbook/compiler-options.html)

Again, this is not my preferred approach and I recommend you overcome the learning curve and follow the first step. I'm happy to keep providing support, but this really comes down to personal preference.

**Comment by ghost** [comment]
Thanks for the tip!

**Comment by ghost** [comment]
Project isn't actually very big btw. Just a hobby and so far this is the
only thing that works to keep GPT from becoming divergent.

‪On Tue, Aug 24, 2021 at 2:48 PM ‫עינ הרע‬‎ ***@***.***>
wrote:‬

**Comment by FurkanToprak** [comment]
Good luck!

**Comment by ghost** [comment]
var BM25 = require("okapibm25").default; // This has to be .default
var documents = [
    "place",
    "documents",
    "here",
    "Each test document will be searched with the keywords specified below."
,
];
var query = ["keywords", "of", "your", "query."];
// A numerical scoring will be returned.
var result = BM25(documents, query, { k1: 1.3, b: 0.9 });
console.log(result);
